{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vprofile-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: vproapp
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: vproapp
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: vproapp-metrics
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.path }}
      honorLabels: true
{{- end }}
####