apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
  labels:
    app: vproapp
spec:
  ports:
  - name: vproapp-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: vproapp-metrics
    port: 9404
    protocol: TCP
    targetPort: 9404
  selector:
    app: vproapp
  type: ClusterIP
